# Generated by Django 5.2.17 on 2026-09-25 07:08

import portal.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', portal.models.EmailUserManager()),
            ],
        ),
    ]
