# Generated by Django 5.2.17 on 2026-09-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_file',
            field=models.FileField(blank=True, upload_to='company_logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_file',
            field=models.FileField(blank=True, upload_to='resumes/%Y/%m/'),
        ),
    ]
