# Generated by Django 5.2.17 on 2026-09-25 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_company_logo_file_seekerprofile_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('REGISTER', 'Registration'), ('JOB_CREATED', 'Job created'), ('JOB_UPDATED', 'Job updated'), ('JOB_CLOSED', 'Job closed'), ('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_STATUS_CHANGED', 'Application status changed'), ('RESUME_UPLOADED', 'Resume uploaded'), ('LOGO_UPLOADED', 'Logo uploaded'), ('USER_DEACTIVATED', 'User deactivated')], db_index=True, max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=60)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='portal_audi_actor_i_ff05b7_idx'), models.Index(fields=['action', '-created_at'], name='portal_audi_action_9645bd_idx')],
            },
        ),
    ]
