# Generated by Django 5.2.17 on 2026-09-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('REGISTER', 'Registration'), ('WELCOME_EMAIL_SENT', 'Welcome email sent'), ('WELCOME_EMAIL_FAILED', 'Welcome email failed'), ('JOB_CREATED', 'Job created'), ('JOB_UPDATED', 'Job updated'), ('JOB_CLOSED', 'Job closed'), ('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_STATUS_CHANGED', 'Application status changed'), ('RESUME_UPLOADED', 'Resume uploaded'), ('LOGO_UPLOADED', 'Logo uploaded'), ('USER_DEACTIVATED', 'User deactivated')], db_index=True, max_length=40),
        ),
    ]
